// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "933cd38f-16b9-4ecf-9e0e-cf1804acce5f");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1354);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563959531);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{17db57fa-b093-4cde-9cfb-b8bb0426386f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.search.region", "AU");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1563959546");
user_pref("browser.slowStartup.averageTime", 13098);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190706141545");
user_pref("browser.startup.homepage_override.mstone", "68.0");
user_pref("browser.startup.lastColdStartupCheck", 1563959534);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "4c1245ced5da49fdb9839b3c8c9866a8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0");
user_pref("extensions.lastPlatformVersion", "68.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a93866b3-3238-4955-80e6-f48149c9ad3b\",\"fxmonitor@mozilla.org\":\"f4c99ed3-a412-4a2d-a027-6f6a8f7f6eac\",\"screenshots@mozilla.org\":\"ac3d645d-094d-4bb3-8f8a-696b2d7bd690\",\"webcompat-reporter@mozilla.org\":\"c3bbc3d1-8275-4a36-92b2-1b4ab06ae1b8\",\"webcompat@mozilla.org\":\"50a579a1-4a3b-4061-baf6-32e63630ccaa\",\"default-theme@mozilla.org\":\"33e47333-5cac-4943-a1e0-1d2edaa156fc\",\"google@search.mozilla.org\":\"a70dbbdb-a549-4b26-aa3e-c463f2db35b3\",\"amazondotcom@search.mozilla.org\":\"f723c5d2-7a29-4f48-b02a-21fdcb71f72a\",\"bing@search.mozilla.org\":\"96a6f7ba-69ef-470a-9e5f-2d9467946c6b\",\"ddg@search.mozilla.org\":\"344da8f5-a415-46ea-b22f-1b1e75e57ca1\",\"ebay@search.mozilla.org\":\"03a2c95e-fcbb-4f3e-9323-1fae17012e3f\",\"twitter@search.mozilla.org\":\"851fb376-8730-4534-9e61-da51b54ba5a9\",\"wikipedia@search.mozilla.org\":\"3406eb00-8e40-4d67-963e-ea5a575f3c7f\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f1ce8682-c858-44b5-954c-61eb76dc7e51");
user_pref("security.sandbox.plugin.tempDirSuffix", "b4e9a6c6-e646-47a8-808e-1f75c573e55a");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1563959521);
user_pref("toolkit.telemetry.cachedClientID", "4d860d5f-dbe1-4b7f-9b71-f2b7908739ff");
user_pref("toolkit.telemetry.previousBuildID", "20190706141545");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
